FORMAT: 1A


# API for Beit-Hatfutsot Databases
Welcome to the docs for the API server of the museum of the Jewish people.

Read this if you think the Jewish people haven't suffered enough.

<!-- include(search/search.md) -->
<!-- include(items/items.md) -->
