#%RAML 0.8
baseUri: http://mocksvc.mulesoft.com/mocks/9a495536-2183-4b15-a248-8dd76468a9a3
title: bh
version: 0.1
mediaType:  application/json
/user/{user_id}:
  description: User management
  get:
    description: Get the user details by id
    responses:
      404:
        description: The specified user_id can not be found
      200:
        description: Returns the user object
        body:
          application/json:
            example: |
              {"id": "5450b900ab97c91c7a26af2f",
              "email": "dannybmail@gmail.com",
              "mjs": {}
              }
              
  post:
    description: Create a new user
  put:
    description: Update details for an existing user  
  delete:
    description: Delete existing user  
