#!/bin/sh
# this file should be in /etc/init.d to allow the user control over 
# the uwsgi service using `service uwsgi [start|stop|restart|status]`
### BEGIN INIT INFO
# Provides:          uwsgi
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the uwsgi application server
# Description:       starts uwsgi using start-stop-daemon
### END INIT INFO

HOME=/home/bhs/api
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/uwsgi
NAME=uwsgi
DESC=uwsgi
LOG_FILE=/var/log/uwsgi.log
PID_FILE=/var/run/bhs/$NAME.pid
DAEMON_OPTS="--pidfile $PID_FILE --ini /etc/bhs/api-uwsgi.ini --daemonize $LOG_FILE"

test -x $DAEMON || (echo "$DAEMON not found" && exit 1)

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet -d $HOME -p $PID_FILE \
            --exec $DAEMON -- $DAEMON_OPTS || true
        echo "$NAME."
        ;;

    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet -d $HOME -p $PID_FILE \
            --exec $DAEMON || true
        echo "$NAME."
        ;;
    reload)
        echo "Reloading $NAME conf"
        kill -HUP $(cat $PID_FILE)
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --quiet -d $HOME -p $PID_FILE --exec $DAEMON || true
        sleep 1
        start-stop-daemon --start --quiet -d $HOME -p $PID_FILE --exec $DAEMON -- $DAEMON_OPTS || true
        echo "$NAME."
        ;;

    status)
        status_of_proc -p $PID_FILE "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|}" >&2
        exit 1
        ;;
esac

exit 0

