#!/bin/sh

### BEGIN INIT INFO
# Provides:          uwsgi
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the uwsgi application server
# Description:       starts uwsgi using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/uwsgi
NAME=uwsgi
DESC=uwsgi
LOG_FILE=/var/log/uwsgi.log
PID_FILE=/var/run/$NAME.pid
DAEMON_OPTS="--emperor /etc/uwsgi/vassals/ --daemonize $LOG_FILE --emperor-pidfile $PID_FILE"

test -x $DAEMON || (echo "$DAEMON not found" && exit 1)

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet \
            --exec $DAEMON -- $DAEMON_OPTS || true
        echo "$NAME."
        ;;

    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet \
            --exec $DAEMON || true
        echo "$NAME."
        ;;
    reload)
        echo "Reloading $NAME conf"
        kill -HUP $(cat $PID_FILE)
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --quiet --exec $DAEMON || true
        sleep 1
        start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS || true
        echo "$NAME."
        ;;

    status)
        status_of_proc -p $PID_FILE "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|}" >&2
        exit 1
        ;;
esac

exit 0

