#!/bin/bash

if [ $1 ]
then
    # dump the items starting with 'B' in all-but-genTreeI collections
    for c in photoUnits movies personalities places familyNames
    do
        mongodump --db $1 --query '{"Header.En" : /^B/}' --collection $c
    done
    # save a backup in tmp
    mongodump --quiet --db $1 --query '{"GTN": 3372}' --collection genTreeIndividuals -o /tmp
    # remove info of the living
    mongo $1 scripts/dump_to_dev.js > /dev/null
    mongodump --quiet --db $1 --query '{"GTN": 3372}' --collection genTreeIndividuals
    rm -rf dump/bhdata
    mv dump/$1 dump/bhdata
    tar cz dump/bhdata
    mongorestore --quiet --db $1 --collection genTreeIndividuals /tmp/$1
else
    echo "dump to dev tar ball"
    echo "Usage: dump_to_dev [dbname] > [out_file]"
    echo "i.e.: dump_to_dev bhdata > [bhs_dev_db.tar.gz]"
fi
